services:
  web:
    build: .
    container_name: my_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  db:
    image: mariadb:10.4.32
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - my_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: my_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"

volumes:
  my_db_data: